"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runAdministrativeProcess = exports.getAllRegisteredModuleIds = exports.getModuleDefinition = exports.getModulesForPhase = exports.registerModule = exports.dispatchModule = void 0;
var flow_dispatcher_1 = require("./flow-dispatcher");
Object.defineProperty(exports, "dispatchModule", { enumerable: true, get: function () { return flow_dispatcher_1.dispatchModule; } });
var flow_registry_1 = require("./flow-registry");
Object.defineProperty(exports, "registerModule", { enumerable: true, get: function () { return flow_registry_1.registerModule; } });
Object.defineProperty(exports, "getModulesForPhase", { enumerable: true, get: function () { return flow_registry_1.getModulesForPhase; } });
Object.defineProperty(exports, "getModuleDefinition", { enumerable: true, get: function () { return flow_registry_1.getModuleDefinition; } });
Object.defineProperty(exports, "getAllRegisteredModuleIds", { enumerable: true, get: function () { return flow_registry_1.getAllRegisteredModuleIds; } });
var administrative_process_engine_1 = require("./administrative-process-engine");
Object.defineProperty(exports, "runAdministrativeProcess", { enumerable: true, get: function () { return administrative_process_engine_1.runAdministrativeProcess; } });
