"use strict";
/**
 * Códigos fechados do regime-behavior-engine (decisão normativa determinística).
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BASIC_MODE_RESTRICTED_CAPABILITY_IDS = exports.REGIME_BEHAVIOR_TRIGGER_CODES = exports.REGIME_BEHAVIOR_WARNING_CODES = exports.REGIME_BEHAVIOR_BLOCKING_REASON_CODES = exports.REGIME_BEHAVIOR_DECISION_STATUS = exports.DOCUMENT_POLICY_LEVEL = exports.RECOGNIZED_LEGAL_REGIME = exports.EXECUTION_SOURCE = exports.REGIME_BEHAVIOR_DECISION_MODE = void 0;
exports.REGIME_BEHAVIOR_DECISION_MODE = {
    BASIC: 'basic',
    FULL: 'full',
};
exports.EXECUTION_SOURCE = {
    STANDARD_EXECUTION: 'standard_execution',
    PREFLIGHT: 'preflight',
};
exports.RECOGNIZED_LEGAL_REGIME = {
    LICITACAO: 'LICITACAO',
    DISPENSA: 'DISPENSA',
    INEXIGIBILIDADE: 'INEXIGIBILIDADE',
};
/** Políticas de obrigatoriedade documental por módulo do pipeline. */
exports.DOCUMENT_POLICY_LEVEL = {
    REQUIRED: 'required',
    OPTIONAL: 'optional',
    CONDITIONAL_REQUIRED: 'conditional_required',
    REQUIRED_ADAPTED: 'required_adapted',
    NOT_APPLICABLE: 'not_applicable',
};
exports.REGIME_BEHAVIOR_DECISION_STATUS = {
    OK: 'ok',
    BLOCKED: 'blocked',
    DEGRADED: 'degraded',
};
/** Códigos de bloqueio normativo (motor). */
exports.REGIME_BEHAVIOR_BLOCKING_REASON_CODES = {
    REGIME_UNRECOGNIZED: 'REGIME_UNRECOGNIZED',
    REGIME_MODALITY_INCOMPATIBLE: 'REGIME_MODALITY_INCOMPATIBLE',
    REGIME_FUNDAMENTO_MINIMO_AUSENTE: 'REGIME_FUNDAMENTO_MINIMO_AUSENTE',
    REGIME_PRICING_EXIGIDO_AUSENTE: 'REGIME_PRICING_EXIGIDO_AUSENTE',
    REGIME_PRICING_INSUFICIENTE: 'REGIME_PRICING_INSUFICIENTE',
    REGIME_INVIABILITY_SUPPORT_AUSENTE: 'REGIME_INVIABILITY_SUPPORT_AUSENTE',
    REGIME_ORDINARY_COMPETITION_INCOMPATIBLE: 'REGIME_ORDINARY_COMPETITION_INCOMPATIBLE',
};
exports.REGIME_BEHAVIOR_WARNING_CODES = {
    BASIC_MODE_NORMATIVE_SCOPE_REDUCED: 'BASIC_MODE_NORMATIVE_SCOPE_REDUCED',
};
exports.REGIME_BEHAVIOR_TRIGGER_CODES = {
    MATRIX_APPLIED: 'MATRIX_APPLIED',
    MODE_RESOLVED: 'MODE_RESOLVED',
    REGIME_RESOLVED: 'REGIME_RESOLVED',
    POLICY_EVALUATED: 'POLICY_EVALUATED',
};
/** Capacidades não reivindicáveis em modo basic (preflight). */
exports.BASIC_MODE_RESTRICTED_CAPABILITY_IDS = [
    'NORMATIVE_MATRIX_FULL_RESOLUTION',
    'CALCULATION_POLICY_FULL',
    'STRATEGY_POLICY_FULL',
    'OBJECT_STRUCTURE_POLICY_FULL',
];
